### ISSUE TITLE
Timed out waiting for YubiKey to set status

### ISSUE THREAD

**Issue by fossxplorer** [greenhost/yubi-goog#1]
After programming slot 2 with the GUI, i'm trying to run yubi_goog.py which times out:
python ./yubi_goog.py yubi
Traceback (most recent call last):
  File "./yubi_goog.py", line 243, in <module>
    main()
  File "./yubi_goog.py", line 227, in main
    ytg_yubi(args['slot'], args['digits'])
  File "./yubi_goog.py", line 124, in ytg_yubi
    token = _gen_token(yubi_slot, digits)
  File "./yubi_goog.py", line 105, in _gen_token
    response = yk.challenge_response(secret, slot=yubi_slot)
  File "/home/susinths/usit/virtualenvs/ansibletest/lib/python2.7/site-packages/yubico/yubikey_usb_hid.py", line 461, in challenge_response
    return self._challenge_response(challenge, mode, slot, variable, may_block)
  File "/home/susinths/usit/virtualenvs/ansibletest/lib/python2.7/site-packages/yubico/yubikey_usb_hid.py", line 521, in _challenge_response
    response = self._device._read_response(may_block=may_block)
  File "/home/susinths/usit/virtualenvs/ansibletest/lib/python2.7/site-packages/yubico/yubikey_usb_hid.py", line 166, in _read_response
    res = self._waitfor_set(yubikey_defs.RESP_PENDING_FLAG, may_block)[:7]
  File "/home/susinths/usit/virtualenvs/ansibletest/lib/python2.7/site-packages/yubico/yubikey_usb_hid.py", line 258, in _waitfor_set
    return self._waitfor('and', mask, may_block)
  File "/home/susinths/usit/virtualenvs/ansibletest/lib/python2.7/site-packages/yubico/yubikey_usb_hid.py", line 310, in _waitfor
    raise yubikey_base.YubiKeyTimeout(reason)
yubico.yubikey_base.YubiKeyTimeout: <YubiKeyTimeout instance at 0x7f8a99998140: Timed out waiting for YubiKey to set status 0x40>

Any hint to solve the issue is highly appreciated!

EDIT1: using Yubikey II. 
It works fine with https://github.com/Ramblurr/yubi-goog, but not with this version in this repo.

**Comment by SnijderC** [comment]
You have programmed slot 2 and seem to have executed 
```
python ./yubi_goog.py yubi
```

That should read from slot 1 by default, can you try:

```
python ./yubi_goog.py yubi --slot 2
```

to actually use slot 2. Please let me know if you experience any more issues, also see: https://github.com/greenhost/yubi-goog#other-options
